# Generated by Django 3.2 on 2021-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True)),
            ],
        ),
    ]
