# Generated by Django 3.2 on 2021-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam_app', '0002_location_scooters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='scooters',
            field=models.IntegerField(default=0),
        ),
    ]
